### ISSUE TITLE
小米4点击选择文件

### ISSUE THREAD

**Issue by mundane799699** [TonnyL/Charles#1]
``` shell

02-09 13:37:41.063 16878-16944/io.github.tonnyl.sample E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
                                                                         Process: io.github.tonnyl.sample, PID: 16878
                                                                         java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                             at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: java.lang.IllegalArgumentException: the bind value at index 8 is null
                                                                             at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
                                                                             at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                             at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                             at android.content.ContentResolver.query(ContentResolver.java:502)
                                                                             at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:80)
                                                                             at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:61)
                                                                             at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:39)
                                                                             at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
                                                                             at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
                                                                             at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
                                                                             at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                             at java.lang.Thread.run(Thread.java:818) 
```
![image](https://user-images.githubusercontent.com/17701628/36013429-1e25317c-0d9f-11e8-9257-2d21dd58f201.png)

**Comment by TonnyL** [comment]
这么难受吗😂 我先看看

**Comment by ultranumblol** [comment]
选择文件类型 the bind value at index 8 is null  这个错误还是有啊

**Comment by TonnyL** [comment]
@ultranumblol 还没有修复， 另外现在Charles还处于alpha阶段，不建议在生产类项目中使用
