### ISSUE TITLE
java.lang.IllegalStateException: MimeTypeMap.getSingleton…mMimeType(audio.mimeType) must not be null

### ISSUE THREAD

**Issue by VeerHan** [TonnyL/Charles#5]
04-13 17:19:39.918 9059-9059/io.github.tonnyl.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.tonnyl.sample, PID: 9059
    java.lang.IllegalStateException: MimeTypeMap.getSingleton…mMimeType(audio.mimeType) must not be null
        at io.github.tonnyl.charles.ui.adapter.MediaItemsAdapter.onBindViewHolder(MediaItemsAdapter.kt:142)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:885)
        at android.view.View.layout(View.java:19781)
        at android.view.ViewGroup.layout(ViewGroup.java:6136)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2655)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2358)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1511)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7198)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)

**Comment by TonnyL** [comment]
Hi, @leoleohan 

What's Android version that the library is running on?

**Comment by leoleohan** [comment]
android 8.0
Huawei mate9
